version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: smartfarm_db
      POSTGRES_USER: iotproject
      POSTGRES_PASSWORD: WeWillDieForIoT
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql

volumes:
  pgdata: